### ISSUE TITLE
Conflict with Vanilla Expanded Framework 

### ISSUE THREAD

**Issue by tomchang25** [kittycat2002/rimworld-showhair#2]
Vanilla Expanded Framework
https://steamcommunity.com/workshop/filedetails/?id=2023507013

## Test1. load with Vanilla Expanded Framework

Not working. Hat is still there.
```
log:
https://gist.github.com/HugsLibRecordKeeper/9f5708db979377c9e474f4ab886332a2

detail log:
https://gist.github.com/HugsLibRecordKeeper/7ddb0c36962b321d3a724611ad326369
```

## Test2. Same mod list without Vanilla Expanded Framework

Working fine. Hat is invisible and hair looks ok now.
```
log:
https://gist.github.com/7c4da16e933c595ccaac5cb78ad75ca5
```

**Comment by kittycat2002** [comment]
Thank you for the report, this issue has been resolved.
